"""GoalCoach domain package exposing core domain models, enums, and retention mathematics."""

from goalcoach.domain.enums import (
    EventType,
    PlanItemKind,
    PlanStatus,
    TeachingActionKind,
)
from goalcoach.domain.events import (
    AnswerSubmittedPayload,
    GoalCreatedPayload,
    HelpRequestedPayload,
    InboundEvent,
    SessionEndedPayload,
    SessionStartedPayload,
)
from goalcoach.domain.models import (
    ActiveLearningSession,
    AgentHistorySummary,
    ConceptMastery,
    DailyPlan,
    DomainBaseModel,
    ErrorRecord,
    Exercise,
    GradingResult,
    LearnerState,
    LearningGoal,
    PlanItem,
    PlanUpdate,
    RubricScores,
    Score,
    SessionSummary,
    TeachingAction,
    TeachingHistoryTurn,
    utc_now,
)
from goalcoach.domain.retention import calculate_retention, decayed_retention

__all__ = [
    "ActiveLearningSession",
    "AgentHistorySummary",
    "AnswerSubmittedPayload",
    "ConceptMastery",
    "DailyPlan",
    "DomainBaseModel",
    "ErrorRecord",
    "EventType",
    "Exercise",
    "GoalCreatedPayload",
    "GradingResult",
    "HelpRequestedPayload",
    "InboundEvent",
    "LearnerState",
    "LearningGoal",
    "PlanItem",
    "PlanItemKind",
    "PlanStatus",
    "PlanUpdate",
    "RubricScores",
    "Score",
    "SessionEndedPayload",
    "SessionStartedPayload",
    "SessionSummary",
    "TeachingAction",
    "TeachingActionKind",
    "TeachingHistoryTurn",
    "calculate_retention",
    "decayed_retention",
    "utc_now",
]
