"""                                                                                                                                                                                                                   
scripts/ingest_curriculum.py                                                                                                                                                                                          
Canonical entrypoint forwarding to CurriculumVectorStore.                                                                                                                                                             
"""                                                                                                                                                                                                                   
                                                                                                                                                                                                                        
from __future__ import annotations                                                                                                                                                                                    
                                                                                                                                                                                                                        
import sys                                                                                                                                                                                                            
from pathlib import Path                                                                                                                                                                                              
                                                                                                                                                                                                                        
PROJECT_ROOT = Path(__file__).resolve().parents[1]                                                                                                                                                                    
if str(PROJECT_ROOT / "src") not in sys.path:                                                                                                                                                                         
    sys.path.insert(0, str(PROJECT_ROOT / "src"))                                                                                                                                                                     
                                                                                                                                                                                                                        
from scripts.vector_store import CurriculumVectorStore                                                                                                                                                                
                                                                                                                                                                                                                        
if __name__ == "__main__":                                                                                                                                                                                            
    store = CurriculumVectorStore()                                                                                                                                                                                   
    store.sync()