"""                                                                                                                                                                                                                   
scripts/observer.py                                                                                                                                                                                                   
Object-Oriented Watchdog to monitor SQLite database changes and sync ChromaDB.                                                                                                                                        
"""                                                                                                                                                                                                                   
                                                                                                                                                                                                                        
from __future__ import annotations                                                                                                                                                                                    
                                                                                                                                                                                                                        
import logging                                                                                                                                                                                                        
import os                                                                                                                                                                                                             
import sys                                                                                                                                                                                                            
import time                                                                                                                                                                                                           
from pathlib import Path                                                                                                                                                                                              
from watchdog.events import FileSystemEvent, FileSystemEventHandler                                                                                                                                                   
from watchdog.observers import Observer                                                                                                                                                                               
                                                                                                                                                                                                                        
PROJECT_ROOT = Path(__file__).resolve().parents[1]                                                                                                                                                                    
if str(PROJECT_ROOT / "src") not in sys.path:                                                                                                                                                                         
    sys.path.insert(0, str(PROJECT_ROOT / "src"))                                                                                                                                                                     
                                                                                                                                                                                                                        
from scripts.vector_store import CurriculumVectorStore                                                                                                                                                                
                                                                                                                                                                                                                        
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")                                                                                                                             
logger = logging.getLogger(__name__)                                                                                                                                                                                  
                                                                                                                                                                                                                        
                                                                                                                                                                                                                        
class DBChangeEventHandler(FileSystemEventHandler):                                                                                                                                                                   
    """Event handler with throttling/cooldown to avoid rapid multiple triggers."""                                                                                                                                    
                                                                                                                                                                                                                        
    def __init__(self, vector_store: CurriculumVectorStore, cooldown_seconds: float = 3.0) -> None:                                                                                                                   
        super().__init__()                                                                                                                                                                                            
        self.vector_store = vector_store                                                                                                                                                                              
        self.cooldown_seconds = cooldown_seconds                                                                                                                                                                      
        self.last_run = 0.0                                                                                                                                                                                           
                                                                                                                                                                                                                        
    def on_modified(self, event: FileSystemEvent) -> None:                                                                                                                                                            
        if event.is_directory:                                                                                                                                                                                        
            return                                                                                                                                                                                                    
                                                                                                                                                                                                                        
        filename = os.path.basename(event.src_path)                                                                                                                                                                   
        if filename.endswith((".db", ".sql", ".db-wal")):                                                                                                                                                             
            now = time.time()                                                                                                                                                                                         
            if now - self.last_run < self.cooldown_seconds:                                                                                                                                                           
                return                                                                                                                                                                                                
            self.last_run = now                                                                                                                                                                                       
                                                                                                                                                                                                                        
            logger.info("Detected database change in: %s", filename)                                                                                                                                                  
            self.trigger_sync()                                                                                                                                                                                       
                                                                                                                                                                                                                        
    def trigger_sync(self) -> None:                                                                                                                                                                                   
        """Executes vector store synchronization."""                                                                                                                                                                  
        logger.info("Triggering vector store sync...")                                                                                                                                                                
        try:                                                                                                                                                                                                          
            self.vector_store.sync()                                                                                                                                                                                  
        except Exception as exc:                                                                                                                                                                                      
            logger.exception("Watcher vector sync failed: %s", exc)                                                                                                                                                   
                                                                                                                                                                                                                        
                                                                                                                                                                                                                        
class CurriculumObserver:                                                                                                                                                                                             
    """Manages the directory watcher lifecycle."""                                                                                                                                                                    
                                                                                                                                                                                                                        
    def __init__(self, watch_dir: Path, vector_store: Optional[CurriculumVectorStore] = None) -> None:                                                                                                                
        self.watch_dir = watch_dir                                                                                                                                                                                    
        self.vector_store = vector_store or CurriculumVectorStore()                                                                                                                                                   
        self.event_handler = DBChangeEventHandler(vector_store=self.vector_store)                                                                                                                                     
        self.observer = Observer()                                                                                                                                                                                    
                                                                                                                                                                                                                        
    def start(self) -> None:                                                                                                                                                                                          
        """Starts monitoring the target directory."""                                                                                                                                                                 
        if not self.watch_dir.exists():                                                                                                                                                                               
            self.watch_dir.mkdir(parents=True, exist_ok=True)                                                                                                                                                         
                                                                                                                                                                                                                        
        self.observer.schedule(self.event_handler, path=str(self.watch_dir), recursive=True)                                                                                                                          
        self.observer.start()                                                                                                                                                                                         
        logger.info("Monitoring for database changes in: %s", self.watch_dir)                                                                                                                                         
        logger.info("Press Ctrl+C to stop.")                                                                                                                                                                          
                                                                                                                                                                                                                        
        try:                                                                                                                                                                                                          
            while True:                                                                                                                                                                                               
                time.sleep(1)                                                                                                                                                                                         
        except KeyboardInterrupt:                                                                                                                                                                                     
            self.stop()                                                                                                                                                                                               
                                                                                                                                                                                                                        
    def stop(self) -> None:                                                                                                                                                                                           
        """Stops the directory monitor gracefully."""                                                                                                                                                                 
        logger.info("Shutting down observer...")                                                                                                                                                                      
        self.observer.stop()                                                                                                                                                                                          
        self.observer.join()                                                                                                                                                                                          
        logger.info("Observer stopped.")                                                                                                                                                                              
                                                                                                                                                                                                                        
                                                                                                                                                                                                                        
if __name__ == "__main__":                                                                                                                                                                                            
    db_monitor_dir = PROJECT_ROOT / "data" / "database1"                                                                                                                                                              
    watcher = CurriculumObserver(watch_dir=db_monitor_dir)                                                                                                                                                            
    watcher.start()