"""                                                                                                                                                                                                                   
scripts/vector_store.py                                                                                                                                                                                               
Object-Oriented Manager to bootstrap and refresh the Chroma vector store via CardChunkFactory.                                                                                                                        
"""                                                                                                                                                                                                                   
                                                                                                                                                                                                                        
from __future__ import annotations                                                                                                                                                                                    
                                                                                                                                                                                                                        
import logging                                                                                                                                                                                                        
import os                                                                                                                                                                                                             
import sys                                                                                                                                                                                                            
import sqlite3                                                                                                                                                                                                        
from pathlib import Path                                                                                                                                                                                              
from typing import Any, List, Optional, Tuple                                                                                                                                                                         
                                                                                                                                                                                                                        
os.environ.setdefault("ANONYMIZED_TELEMETRY", "false")                                                                                                                                                                
os.environ.setdefault("HF_HUB_DISABLE_TELEMETRY", "1")                                                                                                                                                                
                                                                                                                                                                                                                        
PROJECT_ROOT = Path(__file__).resolve().parents[1]                                                                                                                                                                    
if str(PROJECT_ROOT / "src") not in sys.path:                                                                                                                                                                         
    sys.path.insert(0, str(PROJECT_ROOT / "src"))                                                                                                                                                                     
                                                                                                                                                                                                                        
import chromadb                                                                                                                                                                                                       
from chromadb.utils import embedding_functions                                                                                                                                                                        
                                                                                                                                                                                                                        
from goalcoach.infrastructure.config import Settings                                                                                                                                                                  
from goalcoach.infrastructure.retrieval.chunk_factory import CardChunkFactory, CardChunk                                                                                                                              
                                                                                                                                                                                                                        
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")                                                                                                                             
logger = logging.getLogger(__name__)                                                                                                                                                                                  
                                                                                                                                                                                                                        
                                                                                                                                                                                                                        
class CurriculumVectorStore:                                                                                                                                                                                          
    """Manages SQLite curriculum extraction and persistent ChromaDB indexing using CardChunkFactory."""                                                                                                               
                                                                                                                                                                                                                        
    def __init__(                                                                                                                                                                                                     
        self,                                                                                                                                                                                                         
        base_dir: Optional[Path] = None,                                                                                                                                                                              
        collection_name: str = "hsk1_curriculum",                                                                                                                                                                     
        embedding_model: str = "BAAI/bge-small-zh-v1.5",                                                                                                                                                              
        split_examples: bool = False,                                                                                                                                                                                 
        settings: Optional[Settings] = None,                                                                                                                                                                          
    ) -> None:                                                                                                                                                                                                        
        self.settings = settings or Settings()                                                                                                                                                                        
        self.base_dir = (base_dir or PROJECT_ROOT).resolve()                                                                                                                                                          
        self.sqlite_dir = self.base_dir / "data" / "database1"                                                                                                                                                        
        self.vector_store_dir = (self.base_dir / self.settings.vector_store_path).resolve()                                                                                                                           
        self.collection_name = collection_name                                                                                                                                                                        
        self.embedding_model = embedding_model                                                                                                                                                                        
        self.chunk_factory = CardChunkFactory(max_tokens=300, split_examples=split_examples)                                                                                                                          
                                                                                                                                                                                                                        
        self.candidate_db_paths: List[Path] = [                                                                                                                                                                       
            (self.base_dir / self.settings.content_database_path).resolve(),                                                                                                                                          
            self.sqlite_dir / "goalcoach.db",                                                                                                                                                                         
            self.sqlite_dir / "goalcoach_hsk1_learning.db",                                                                                                                                                           
        ]                                                                                                                                                                                                             
                                                                                                                                                                                                                        
        self._client: Optional[chromadb.PersistentClient] = None                                                                                                                                                      
        self._collection: Optional[chromadb.Collection] = None                                                                                                                                                        
                                                                                                                                                                                                                        
    def resolve_sqlite_path(self) -> Path:                                                                                                                                                                            
        for candidate in self.candidate_db_paths:                                                                                                                                                                     
            if candidate.exists():                                                                                                                                                                                    
                return candidate                                                                                                                                                                                      
                                                                                                                                                                                                                        
        checked_paths = "\n  - ".join(str(p) for p in self.candidate_db_paths)                                                                                                                                        
        raise FileNotFoundError(                                                                                                                                                                                      
            f"Could not find curriculum SQLite DB. Checked:\n  - {checked_paths}"                                                                                                                                     
        )                                                                                                                                                                                                             
                                                                                                                                                                                                                        
    def fetch_cards(self, db_path: Path) -> List[Tuple[Any, ...]]:                                                                                                                                                    
        try:                                                                                                                                                                                                          
            with sqlite3.connect(str(db_path)) as conn:                                                                                                                                                               
                cursor = conn.cursor()                                                                                                                                                                                
                try:                                                                                                                                                                                                  
                    query = """                                                                                                                                                                                       
                    SELECT                                                                                                                                                                                            
                        concept_id, sequence_no, title_zh, title_en, communicative_goal,                                                                                                                              
                        card_id, card_type, prompt_zh, explanation_en, example_zh, example_en                                                                                                                         
                    FROM v_teaching_modules                                                                                                                                                                           
                    WHERE card_id IS NOT NULL;                                                                                                                                                                        
                    """                                                                                                                                                                                               
                    cursor.execute(query)                                                                                                                                                                             
                    rows = cursor.fetchall()                                                                                                                                                                          
                    logger.info("Loaded %d cards from v_teaching_modules.", len(rows))                                                                                                                                
                    return rows                                                                                                                                                                                       
                except sqlite3.OperationalError:                                                                                                                                                                      
                    query = """                                                                                                                                                                                       
                    SELECT                                                                                                                                                                                            
                        concept_id, 0, '', '', '',                                                                                                                                                                    
                        card_id, card_type, prompt_zh, explanation_en, example_zh, example_en                                                                                                                         
                    FROM teaching_cards;                                                                                                                                                                              
                    """                                                                                                                                                                                               
                    cursor.execute(query)                                                                                                                                                                             
                    rows = cursor.fetchall()                                                                                                                                                                          
                    logger.info("Loaded %d cards from fallback table 'teaching_cards'.", len(rows))                                                                                                                   
                    return rows                                                                                                                                                                                       
        except sqlite3.Error as err:                                                                                                                                                                                  
            logger.exception("Database extraction failed from %s: %s", db_path, err)                                                                                                                                  
            raise                                                                                                                                                                                                     
                                                                                                                                                                                                                        
    def get_or_create_collection(self) -> chromadb.Collection:                                                                                                                                                        
        if self._collection is not None:                                                                                                                                                                              
            return self._collection                                                                                                                                                                                   
                                                                                                                                                                                                                        
        self.vector_store_dir.mkdir(parents=True, exist_ok=True)                                                                                                                                                      
        self._client = chromadb.PersistentClient(path=str(self.vector_store_dir))                                                                                                                                     
        embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(                                                                                                                                      
            model_name=self.embedding_model                                                                                                                                                                           
        )                                                                                                                                                                                                             
                                                                                                                                                                                                                        
        self._collection = self._client.get_or_create_collection(                                                                                                                                                     
            name=self.collection_name,                                                                                                                                                                                
            embedding_function=embedding_fn,                                                                                                                                                                          
            metadata={"hnsw:space": "cosine"},                                                                                                                                                                        
        )                                                                                                                                                                                                             
        return self._collection                                                                                                                                                                                       
                                                                                                                                                                                                                        
    def sync(self) -> Tuple[str, int]:                                                                                                                                                                                
        sqlite_path = self.resolve_sqlite_path()                                                                                                                                                                      
        logger.info("SQLite Source: %s", sqlite_path)                                                                                                                                                                 
        logger.info("Vector Store Path: %s", self.vector_store_dir)                                                                                                                                                   
                                                                                                                                                                                                                        
        collection = self.get_or_create_collection()                                                                                                                                                                  
        status = "existing" if collection.count() > 0 else "new"                                                                                                                                                      
                                                                                                                                                                                                                        
        rows = self.fetch_cards(sqlite_path)                                                                                                                                                                          
        if not rows:                                                                                                                                                                                                  
            raise RuntimeError(f"No records found in {sqlite_path}")                                                                                                                                                  
                                                                                                                                                                                                                        
        all_chunks: List[CardChunk] = []                                                                                                                                                                              
        for row in rows:                                                                                                                                                                                              
            all_chunks.extend(self.chunk_factory.create_chunks_from_row(row))                                                                                                                                         
                                                                                                                                                                                                                        
        ids = [c.chunk_id for c in all_chunks]                                                                                                                                                                        
        documents = [c.text for c in all_chunks]                                                                                                                                                                      
        metadatas = [c.metadata for c in all_chunks]                                                                                                                                                                  
                                                                                                                                                                                                                        
        collection.upsert(ids=ids, documents=documents, metadatas=metadatas)                                                                                                                                          
        total_count = collection.count()                                                                                                                                                                              
        logger.info("Vector Store sync complete. Status: %s -> Final Count: %d chunks.", status, total_count)                                                                                                         
        return status, total_count                                                                                                                                                                                    
                                                                                                                                                                                                                        
                                                                                                                                                                                                                        
if __name__ == "__main__":                                                                                                                                                                                            
    store = CurriculumVectorStore()                                                                                                                                                                                   
    store.sync()